version: "3"

services:
  postgres:
    image: postgres:10.6
    container_name: heart_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heart
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: heart_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 8080:80

  node-api:
    build:
      dockerfile: Dockerfile
      context: ./api
    container_name: heart_node_api
    depends_on:
      - "postgres"
    volumes:
      - ./code/node_modules
      - ./api:/code
    ports:
      - 4000:4000
      - 9229:9229
    command:
      - npm
      - run
      - debug

  node-client:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: heart_node_client
    volumes:
      - ./code/node_modules
      - ./client:/code
    ports:
      - 3000:3000
